name: Run Shell Commands
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo String
        run: echo "Hello Security Gurus!! This is our first GitHub Actions Workflow file"
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true # To run jobs even high severity errors occurs. Otherwise it will fail with high severity error.
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
